name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours 
  workflow_dispatch:       # Allow manual triggering
  push:
    branches:
      - main               # Run on pushes to the main branch

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg # Output to SVG

      - name: Push generated SVG
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
